aws_profile = "power-blox"
aws_region = "eu-west-1"
hosted_zone = "power-blox.cloud."
prototype_hostname = "p01"
namespace = "power-blox"
cognito_identity_pool_name = "webapp"
cognito_identity_pool_provider = "power-blox.cloud"
